### ISSUE TITLE
None of the page links work

### ISSUE THREAD

**Issue by kwcooper** [GCCR/GCCR.github.io#13]
On the jekyl site.

**Comment by kwcooper** [comment]
Phew, no worries I got it

**Comment by cbouy** [comment]
It's weird, it worked (and still works) both with the `.html` extension or with `/` instead on my local environment... 
But looking further in the `_site` folder (where jekyll actually builds the files that will be served by the website), jekyll builds the .html files (i.e. members.html) instead of folders (i.e. members/index.html). Since in the navbar I was using the "folder" links (ending with `/`), none of the link worked on the deployment version. But I'm still curious as for why they worked locally...
I'll push a fix to keep the pretty names (folder structure) in the _config.yml

Sorry for the heart attack @kwcooper !
