### ISSUE TITLE
Update website home design

### ISSUE THREAD

**Issue by kwcooper** [GCCR/GCCR.github.io#15]
And change the Global Cons... header text..

**Comment by mariaveldhuizen** [comment]
align text left, take out italics

**Comment by mariaveldhuizen** [comment]
Here are some more requested specifics for the webpage in general : 


 Colour
We want to stick to the green, because that is now our recognizable colour, but we are going to lighten the style up a bit. Make the buttons about 50% more transparent, so much lighter shade of green. Let’s see a sample.

Content

We want less text overall. Also less white space, because right now a lot of scrolling is necessary.
Keep survey buttons up top, we are discussing this, but not sure what to do about this for now

We want one paragraph of text about who we are:
“How we started (instead of “introduction”)
In response to anecdotal reports of the loss of smell and of taste in people who have tested positive for COVID-19, a group of international smell and taste researchers have united to study how, when and why this is happening and what it can tell us about the Coronavirus.” 
That’s it J. Rest can go.

Then the three icons, but without explanation, just the headings “collaborate, research disseminate”. Make them smaller too.
Then: “If you are a scientist, clinician or patient advocate, join us as a member“ (with link to page “join”).
All text blocks left justified. Headers could be centered or left justified, but probably left justified it best, let’s see a sample?

It is easy to end up scrolling in the map accidentally. Not sure how to solve.

Can we put twitter feed on the right for example? So it is not all the way in the bottom

Remove contact form from landing page, I think this is confusing and people think that they can join GCCR there.

**Comment by cbouy** [comment]
For the map I can display the static image and load the interactive one only if the user clicks on the image (and a "Click on the image to load the interactive map")

**Comment by kwcooper** [comment]
Okay, so I updated the homepage a bit. Cleaned up the introductions and aligned the twitter and the "how we started" section. Moved the map up higher so people can see it, and removed the text in the icons. 

For now, I left the mission text when left aligned, because I think we can keep some of it (albeit thinned down) if we add a news section to the right of it. Once we have some content for the news page, we would want this to be visible on the home page. 

I didn't touch the contact section yet because I think we should just go ahead and make an entire page for contact. I'll open an issue for this shortly. 

Let me know your thoughts and please test it out a bit to see if anything is broken. let me know what else should be changed. Thanks all!

**Comment by cbouy** [comment]
Looks great @kwcooper ! I'll update the color code of the members map to be green so it's more on par with the rest of the design.
