### ISSUE TITLE
Surveys page

### ISSUE THREAD

**Issue by mariaveldhuizen** [GCCR/GCCR.github.io#23]
Left align the flashing welcome message.

Confirm they are in the right place with a sentence like: “Have you had a respiratory illness of any kind recently? Willing to share a bit of information about your experiences? It’s easy and takes about 10 minutes.”  

We don’t need to instruct people to select their language, the buttons do that already.

Make all buttons as wide as the longest word (Nederlands) and left align text inside the buttons (same for buttons on home page)

Text about Penn State left align, “Penn State University in the United States of America”.

There is no obvious home button on this page (though clicking the big logo at the top will take you home). Might be a good idea to make the toolbar visible on the surveys page.  Also, this page is beautiful in its simplicity and is a good example of what participants can relate to.

**Comment by mariaveldhuizen** [comment]
On each language page:
Everything left aligned.
“Share the survey” - bigger and/or lower, hard to see right now
Text about Penn State left align, “Penn State University in the United States of America”

**Comment by cbouy** [comment]
For the buttons as wide as the longest word that's quite a pain to do and i'm not sure about the look of buttons with left aligned text.
For the language pages, left-aligning everything looked quite bad, but it's more readable for the bottom text so I only kept that (or right-aligned for arabic, hebrew...etc).
The rest of your suggestions or done, except for the link to the home page/toolbar I'm not sure what to do about that yet. I also added all translations of "hello" to the flashing welcome messages, not just the 5 or 6 we had manually added.

Survey page:
![Survey page](https://user-images.githubusercontent.com/27850535/81208720-ca1b2400-8fcf-11ea-931e-3ec40ba61fa4.PNG)

Language page:
![Language page](https://user-images.githubusercontent.com/27850535/81208596-9c35df80-8fcf-11ea-9223-08e32f298ece.PNG)

PS: this is not live right now, just on the dev branch

**Comment by kwcooper** [comment]
Thanks for the suggestions. Particularly with the buttons and left align request I think the best solution would be to narrow the width of the page all together. Left align is great on small screen's but looks poor on wide ones. This should be accessible by modifying the div's that wrap the content in the page.

**Comment by kwcooper** [comment]
For the home page suggestion, I suggest modifying the footer GCCR link to saying "GCCR Home" or something similar. We may also recreate the awesome links Cedric built that say "back to language selection" to do something similar. I think adding the toolbar would be out of scope for what these pages are trying to serve.

**Comment by kwcooper** [comment]
I tried to update the share the survey font size a week ago or so, but couldn't find where in the codebase it was pulling from. @cbouy could you let me know for my sanity haha

**Comment by cbouy** [comment]
@kwcooper have a look at [_sass/base/_mixins.scss](https://github.com/GCCR/GCCR.github.io/blob/master/_sass/base/_mixins.scss)

**Comment by cbouy** [comment]
@kwcooper ignore my previous message, it's in [_includes/share-survey.html](https://github.com/GCCR/GCCR.github.io/blob/5be11354b7d5259233b5b73183833b149ca796e8/_includes/share-survey.html#L15)

**Comment by tristramw-uk** [comment]
The landing page (main) and languages has the original, very short and not super informative text, "Participate in the GCCR study" (which only means something to us).
Could we replace that text with the already approved compuserve welcome page text (I know they will see it when they click through to the survey) but we want to encourage people to take the survey so they need to see it when they first land, BEFORE they click through. 
The priority is to change it on the main page.  (individual languages could follow when we have time). 

![welcome-page-compuserve](https://user-images.githubusercontent.com/64918812/81537448-1a460d80-9365-11ea-800d-79ec73a562fa.JPG)

**Comment by cbouy** [comment]
> For the home page suggestion, I suggest modifying the footer GCCR link to saying "GCCR Home" or something similar. We may also recreate the awesome links Cedric built that say "back to language selection" to do something similar. I think adding the toolbar would be out of scope for what these pages are trying to serve.

I agree with Keiland, adding the navigation bar is outside of the original idea (guiding the general audience towards the survey, and chemosensory-related people towards the main website). I could add a "Who are we" or "About us" link just below the "Back to language selection" link. The link would go to the [Introduction](https://gcchemosensr.org/#intro) section of our home page, so they can see the short intro, our mission, twitter feed, the map...etc. (and the upcoming "I care" video ?)

>The landing page (main) and languages has the original, very short and not super informative text, "Participate in the GCCR study" (which only means something to us).

@tristramw-uk I think the idea for the landing page was to make it not too English-dominated, i.e. keep it to the strict minimum. However, we could do that for the language pages as you suggested.

**Comment by kwcooper** [comment]
I worked on this page a smidge, mostly just to increase the font size of the share button and to add a link to the GCCR homepage, and minor updates. 

@cbouy I still, for the life of me, cannot find the "Share the survey" text. I found where it is inherited, `{{ page.share_survey | default: defaults.share_survey }}` and updated that, but where do these pull from? This is now personal haha. 

If we want to left align the text under the survey, we should make two columns. @cbouy is right, left align on a wide scree looks bad. If columns are the answer, we should brainstorm how best to do this. 

@tristramw-uk Thank you for the suggestion. To me though, adding that much text would be a bit much for these pages. The point of the survey pages are to funnel the user's to the appropriate surveys. 

May I ask the motivation behind your suggestion? If it is due to IRB, then that is a different story, and I could build a dropdown, popup, or intermediate page to keep things clean. But if it is just to inform and convince people to take the survey, then I think we should brainstorm a different way to go about it, which strikes the balance between informing and convincing the user to take the survey (which I imagine they are already interested if they made it to the page) and information overload. 

If click-through rate is your concern, I have data for clicks we can consult to see how big of an issue it really is...

**Comment by cbouy** [comment]
> @cbouy I still, for the life of me, cannot find the "Share the survey" text. I found where it is inherited, {{ page.share_survey | default: defaults.share_survey }} and updated that, but where do these pull from? This is now personal haha.

They are all taken from the `_surveys` folder. For each language page, it takes the `share_survey` from the MD file directly, and for the landing page, since it's not built the same way (it's not a language page so there's no `page.share_survey`) it falls back to the `defaults.share_survey` where `defaults` corresponds to the `en.md`:
https://github.com/GCCR/GCCR.github.io/blob/0474ab7ee38e6149a8d0693a24de47cb9bafbd0c/_includes/share-survey.html#L12

**Comment by cbouy** [comment]
@kwcooper is there a reason why the English welcome message appears 2 times in the sequence ?
https://github.com/GCCR/GCCR.github.io/blob/3a66cd693c7ed858f3e838be183e96519a19f71b/surveys/index.html#L46

Also, can I go ahead and replace the sequence by just the "Hello" messages (without the "Select your language") and the "Have you had a respiratory illness of any kind recently? Willing to share a bit of information about your experiences? It’s easy and takes about 10 minutes." ?

**Comment by kwcooper** [comment]
I think we nailed it
