### ISSUE TITLE
new webpage section for published papers

### ISSUE THREAD

**Issue by mariaveldhuizen** [GCCR/GCCR.github.io#36]
We would like a new main menu item called "publications" and there we will link to the paper, and osf page or other page with open materials. I'm creating a google form with the titles, links etc.

**Comment by mariaveldhuizen** [comment]
https://docs.google.com/spreadsheets/d/1pl_NM19DsroHBMYK5WrIcZygLYw8kevbwYZ_CTTl8Ek/edit?usp=sharing

**Comment by mariaveldhuizen** [comment]
@kwcooper I populated the fields in that document (https://docs.google.com/spreadsheets/d/1pl_NM19DsroHBMYK5WrIcZygLYw8kevbwYZ_CTTl8Ek/edit?usp=sharing). With this, can you create a page for our publication, pretty much just like the one you have on your webpage? The last column is something I hope to implement in the future, a tab with a "plain language summary", maybe useful to anticipate. I'm not sure about listing preprints yet, but once you have the structure in place it will be easy for me to just add info in the sheet.

**Comment by kwcooper** [comment]
I built the first draft of the publications page and the backend logic to generate each pub entry. Take a look here and let me know what you think https://gcchemosensr.org/pubs/ @cbouy @mariaveldhuizen It'd be great if you could test it a bit on your devices, to make sure everything is working okay. It should look something like this on your screen: 

![Screenshot from 2021-06-06 05-09-48](https://user-images.githubusercontent.com/17441478/120924466-c18c9580-c688-11eb-9aec-bb136890f505.png)

Each pub is generated from a YAML file, with the hope that others should be able to easily update it. I can go over this in more detail in the future, but it should mostly be pretty self explanatory. You can take a look here: https://github.com/GCCR/GCCR.github.io/blob/master/_data/pubs.yml

Thanks! 😄

**Comment by cbouy** [comment]
Looking good! Just a few comments:

- In commit [b0aa4db](https://github.com/GCCR/GCCR.github.io/commit/b0aa4dbc24531013b16128892b6594081ed9eb4c) you included all the binaries and libraries in the `vendors` directory which I guess are necessary to run the website locally, but it's note really needed for github pages to build. Could you remove them and add a `vendor/` entry to the `.gitignore` file ?
- I think you can remove [this line](https://github.com/GCCR/GCCR.github.io/commit/b0aa4dbc24531013b16128892b6594081ed9eb4c#diff-515ba903e46672f4b154e722c09f81e80e635f6200a2317450dadac29cd78e1eR10) since you don't use it
- In the `pubs.yml` file, I don't think quotes are needed for the abstract and title, they should only be necessary if the sentence starts with a special character. Most importantly I'm not sure how the YAML will be parsed if there's a single or double quote inside the sentence itself...
- I'd directly use the DOI link in the `link` item of each pub, i.e. `https://doi.org/10.1038/s41467-020-18963-y` for the Nat. Commun. and `https://doi.org/10.1093/chemse/bjaa081` for the second Chem. Senses
- My ad-blocker is blocking the images from showing because of the name of the class `pub-img`, `pub` is a short word for advertisement in french, hence the blocking. Could you rename the class as `publication-img` to avoid this ?
- I think you can resize the images to 200px width to cut down on loading time

On my mobile, the `Resources` tab is on a separate line from Info and Abstract, but it's not that big of a deal

**Comment by mariaveldhuizen** [comment]
Looks great in Chrome and on Iphone. I can check with android device tomorrow if you want. I can totally deal with the YAML file. So the google sheet will not be used? @kwcooper @

**Comment by kwcooper** [comment]
Thanks for the comments folks! Super helpful, especially the adblock tip in french haha. I think I got most of @cbouy's suggestions. I can't remove that pesky JS line as the favecon breaks without it it seems. When we have more time we can investigate. Not sure what is up with the random vendors folder. But I added it to the gitignore.  The size of the image is set in CSS, but you're right they could be resized more. Loading time isn't bad on my machine, but we can consider offline resizing the images themselves if we feel it becomes an issue. 

Yeah, mobile is weird because spacing. Might be able to tweak it to work all on one line. But I'm guessing we may add more categories in the future, so it may be a lost cause. 

I used the Google sheet as a reference to populate the yaml file, @mariaveldhuizen,  but I didn't want to spend time getting it to talk to github. More importantly, there are aspects of the code that will have to be updated anyway, such as the path to the image, the ID of the pub, etc, so I though YAML was a happy medium of usability and not too much overhead. It may be good to keep the sheet as a reference though, or to add the info there for someone to update the YAML.

**Comment by kwcooper** [comment]
Speaking of other tabs. Authors, press links, citations, metrics, etc come to mind. It's pretty bare bones for now. I don't think any of these will be paywalled since they're covid papers, but we may consider hosting the PDF's on github if needed too

**Comment by cbouy** [comment]
I actually messed up and you indeed need quotes in the YAML file otherwise if the text contains ":" it will break... My bad
I fixed the remaining issue with the vendor directory. Also I don't see any issue with the favicon on my side, maybe it was a caching issue from your browser?
Good job!

**Comment by kwcooper** [comment]
I'll close this for now, we can make a new issue if we want any updates. Thanks folks!
