### ISSUE TITLE
Copy map to people page, drop down

### ISSUE THREAD

**Issue by kwcooper** [GCCR/GCCR.github.io#4]
@cbouy could copy your map to the people page of the website too? 

Also, would you mind seeing if you could move the long list of countries on your form to a separate file that is called by the form to clean up the code a little? No worries if it becomes too much of a hassle. 

Thank you! Great work!

**Comment by kwcooper** [comment]
For the dropdown, you may want to use this script from SO https://stackoverflow.com/a/38037444 . I used it here: https://github.com/GCCR/GCCR.github.io/blob/master/people.html#L37
 and here: https://github.com/GCCR/GCCR.github.io/blob/master/people.html#L119

**Comment by cbouy** [comment]
Yes I'll take care of that ! Copying or moving ?

Regarding the "cleaning up the code", I'll start to implement Jekyll so that we can include html snippets and use templates for this very purpose. It will make the site much easier to maintain. I also need to modify the list of countries, it doesn't match the one used by the Google form.

Then I'll add a headless CMS (content management system) to make publishing news/blog posts a breeze for the others. I was thinking of one of these solutions:
* [Publii](https://getpublii.com/), which requires to install their software, and authors will have to create a github account and link it to Publii. Completely free and unlimited number of authors though.
* [Forestry](https://forestry.io/), where everything is done online but you can only have 3 authors in the free plan.
The solution that I originally mentioned ([NetlifyCMS](https://www.netlifycms.org/)) only allows a single author account. 
In terms of security I'd prefer avoiding anything that would require a shared account between all authors. What are your thoughts about this ?

**Comment by kwcooper** [comment]
Great thanks! I think copying would work for now, the map looks good on the homepage, but should also show where our members are from on the people page

>  I'll start to implement Jekyll so that we can include html snippets and use templates for this very purpose.

I 100% agree. I really wanted to do this but haven't had too much time. I only didn't start with it because I didn't know how many pages we were going to want. 1 -3 is find but any more updating each one is tedious, thus completing the feeling that I really want to do this! Thank you! Let me know if I can help in some way. 

Re: the blog. I haven't used either. But from the sounds of things I think that Publii may be the best bet for now. I don't think having them make a Github account is out of the question (you'd have to make an account on any other platform, and as a bonus a Github account can be used for much more.)

I have some blog content already that I was going to make a temporary page for, if you like I can post it for you to have something to start with?

**Comment by kwcooper** [comment]
This is superseded by the issue #6
